---
- name: Deploy windows VM in AWS
  hosts: localhost
  vars:
    instance_loc: aws
    name_prefix: "Ansibledemo"
    ec2_vpc_id: "vpc-0bcde310b604499c6"
    ec2_region: "ap-southeast-2"
    ec2_az: "ap-southeast-2a"
    tag_user: "ansible"
    user_count: "1"
    ec2_instance_type: "t2.medium"
    ec2_vpc_subnet_id: "subnet-0b0bfa69219481a33"
    ec2_ami_image: "ami-0be7afce90ae33ee9" #Microsoft Windows Server 2022 Base
    ptr_zone_cidr: "10.10.1.0/24"

  tasks:
    - name: Windows - Launch instance 1
      ec2:
        key_name: "{{ tag_user }}-{{ name_prefix }}-key"
        group: windows
        instance_type: "{{ ec2_instance_type }}"
        count: 1
        image: "{{ ec2_ami_image }}"
        wait: yes
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
        user_data: "{{ lookup('template', 'win_ec2_user_data.j2', template_vars=dict(vm_name='s' + item + '-database')) }}"
        assign_public_ip: yes
