---
- name: Deploy windows VM in AWS
  hosts: localhost
  vars:
    instance_loc: aws
    name_prefix: "Ansibledemo"
    ec2_vpc_id: "vpc-0bcde310b604499c6"
    ec2_region: "ap-southeast-2"
    ec2_az: "ap-southeast-2a"
    tag_user: "ansible"
    user_count: "1"
    ec2_instance_type: "t2.medium"
    ec2_vpc_subnet_id: ""
    ec2_ami_image: "ami-0be7afce90ae33ee9" #Microsoft Windows Server 2022 Base
    ptr_zone_cidr: "10.10.1.0/24"

  tasks:
    - name: Windows - Launch instance 1
      ec2:
        key_name: "{{ tag_user }}-{{ name_prefix }}-key"
        group: "{{ name_prefix }}-windowssg"
        instance_type: "{{ ec2_instance_type }}"
        exact_count: 1
        count_tag:
          Name: "{{ name_prefix + '-s' + item + '-database'}}"
          App: AnsibleWorkshop
        instance_tags:
          Name: "{{ name_prefix + '-s' + item + '-database'}}"
          App: AnsibleWorkshop
          Workshop: "{{ name_prefix }}"
          Username: "{{ tag_user }}"
          Info: "Username that provisioned this-> {{ tag_user }}"
          Students: "{{ user_count }}"
          short_name: "{{ 's' + item + '-database' }}"
          long_name: "{{ 's' + item + '-database' }}.{{ name_prefix }}.{{ public_dns_zone | default('') }}"
          os_type: windows
        image: "{{ ec2_ami_image }}"
        wait: true
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
        user_data: "{{ lookup('template', 'win_ec2_user_data.j2', template_vars=dict(vm_name='s' + item + '-database')) }}"
        assign_public_ip: yes
      with_sequence: count={{user_count}}
      register: windows1_jobs
      async: 7200
      poll: 0
      wait: yes
      wait_timeout: 500
